// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {model} from '../models';

export function AddCredential(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:Array<string>):Promise<string>;

export function AddCredentialFromURI(arg1:string):Promise<string>;

export function ChangePassphrase(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CreateVault(arg1:string,arg2:string):Promise<string>;

export function ExportVault(arg1:string):Promise<Array<number>>;

export function ExportVaultToFile(arg1:string):Promise<string>;

export function GenerateHOTP(arg1:string):Promise<string>;

export function GenerateTOTP(arg1:string):Promise<main.TOTPResult>;

export function GetAuditHistory():Promise<Array<main.AuditHistoryRecord>>;

export function GetConfig():Promise<config.Config>;

export function GetCredential(arg1:string):Promise<model.Credential>;

export function GetIdleTimeoutSeconds():Promise<number>;

export function GetStaticPassword(arg1:string):Promise<void>;

export function GetVersion():Promise<string>;

export function ImportVault(arg1:Array<number>,arg2:string):Promise<number>;

export function ImportVaultFromFile(arg1:string,arg2:string):Promise<main.ImportResult>;

export function IsAuditEnabled():Promise<boolean>;

export function ListCredentials():Promise<Array<model.Credential>>;

export function LockVault():Promise<void>;

export function PickImportFile():Promise<string>;

export function RemoveCredential(arg1:string):Promise<void>;

export function ScanForVaults():Promise<Array<main.VaultLocation>>;

export function ScanRemovableDrives():Promise<Array<main.VaultLocation>>;

export function SetIdleTimeoutSeconds(arg1:number):Promise<void>;

export function SignChallenge(arg1:string,arg2:string):Promise<string>;

export function UnlockVault(arg1:string,arg2:string):Promise<void>;

export function VerifyAuditLog():Promise<main.AuditVerifyResult>;

export function VerifyRecoveryKey(arg1:string):Promise<boolean>;
