// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCredential(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddCredential'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddCredentialFromURI(arg1) {
  return window['go']['main']['App']['AddCredentialFromURI'](arg1);
}

export function ChangePassphrase(arg1, arg2) {
  return window['go']['main']['App']['ChangePassphrase'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateVault(arg1, arg2) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2);
}

export function EnableAudit() {
  return window['go']['main']['App']['EnableAudit']();
}

export function ExportVault(arg1) {
  return window['go']['main']['App']['ExportVault'](arg1);
}

export function ExportVaultToFile(arg1) {
  return window['go']['main']['App']['ExportVaultToFile'](arg1);
}

export function GenerateHOTP(arg1) {
  return window['go']['main']['App']['GenerateHOTP'](arg1);
}

export function GenerateTOTP(arg1) {
  return window['go']['main']['App']['GenerateTOTP'](arg1);
}

export function GetAuditAutoStart() {
  return window['go']['main']['App']['GetAuditAutoStart']();
}

export function GetAuditDockerPath() {
  return window['go']['main']['App']['GetAuditDockerPath']();
}

export function GetAuditHistory() {
  return window['go']['main']['App']['GetAuditHistory']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCredential(arg1) {
  return window['go']['main']['App']['GetCredential'](arg1);
}

export function GetIdleTimeoutSeconds() {
  return window['go']['main']['App']['GetIdleTimeoutSeconds']();
}

export function GetStaticPassword(arg1) {
  return window['go']['main']['App']['GetStaticPassword'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportVault(arg1, arg2) {
  return window['go']['main']['App']['ImportVault'](arg1, arg2);
}

export function ImportVaultFromFile(arg1, arg2) {
  return window['go']['main']['App']['ImportVaultFromFile'](arg1, arg2);
}

export function IsAuditConfigured() {
  return window['go']['main']['App']['IsAuditConfigured']();
}

export function IsAuditEnabled() {
  return window['go']['main']['App']['IsAuditEnabled']();
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function PickImportFile() {
  return window['go']['main']['App']['PickImportFile']();
}

export function RemoveCredential(arg1) {
  return window['go']['main']['App']['RemoveCredential'](arg1);
}

export function ScanForVaults() {
  return window['go']['main']['App']['ScanForVaults']();
}

export function ScanRemovableDrives() {
  return window['go']['main']['App']['ScanRemovableDrives']();
}

export function SetAuditAutoStart(arg1) {
  return window['go']['main']['App']['SetAuditAutoStart'](arg1);
}

export function SetIdleTimeoutSeconds(arg1) {
  return window['go']['main']['App']['SetIdleTimeoutSeconds'](arg1);
}

export function SignChallenge(arg1, arg2) {
  return window['go']['main']['App']['SignChallenge'](arg1, arg2);
}

export function StartAuditServer() {
  return window['go']['main']['App']['StartAuditServer']();
}

export function StopAuditServer(arg1) {
  return window['go']['main']['App']['StopAuditServer'](arg1);
}

export function UnlockVault(arg1, arg2) {
  return window['go']['main']['App']['UnlockVault'](arg1, arg2);
}

export function VerifyAuditLog() {
  return window['go']['main']['App']['VerifyAuditLog']();
}

export function VerifyRecoveryKey(arg1) {
  return window['go']['main']['App']['VerifyRecoveryKey'](arg1);
}
