// Subset of the ScalarDL 3.12 proto definitions used by the Tegata audit layer.
// Source: https://github.com/scalar-labs/scalardl/blob/v3.12.0/rpc/src/main/proto/scalar.proto
// Only the message types and RPCs required by Tegata are included.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: scalar.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	KeyVersion    uint32                 `protobuf:"varint,2,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	CertPem       string                 `protobuf:"bytes,3,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRegistrationRequest) Reset() {
	*x = CertificateRegistrationRequest{}
	mi := &file_scalar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRegistrationRequest) ProtoMessage() {}

func (x *CertificateRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CertificateRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateRegistrationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CertificateRegistrationRequest) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *CertificateRegistrationRequest) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

type SecretRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	KeyVersion    uint32                 `protobuf:"varint,2,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	SecretKey     string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRegistrationRequest) Reset() {
	*x = SecretRegistrationRequest{}
	mi := &file_scalar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRegistrationRequest) ProtoMessage() {}

func (x *SecretRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRegistrationRequest.ProtoReflect.Descriptor instead.
func (*SecretRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{1}
}

func (x *SecretRegistrationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SecretRegistrationRequest) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *SecretRegistrationRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type ContractExecutionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContractId       string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	ContractArgument string                 `protobuf:"bytes,2,opt,name=contract_argument,json=contractArgument,proto3" json:"contract_argument,omitempty"`
	EntityId         string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	KeyVersion       uint32                 `protobuf:"varint,4,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	FunctionArgument string                 `protobuf:"bytes,5,opt,name=function_argument,json=functionArgument,proto3" json:"function_argument,omitempty"`
	Signature        []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	AuditorSignature []byte                 `protobuf:"bytes,7,opt,name=auditor_signature,json=auditorSignature,proto3" json:"auditor_signature,omitempty"`
	UseFunctionIds   bool                   `protobuf:"varint,8,opt,name=use_function_ids,json=useFunctionIds,proto3" json:"use_function_ids,omitempty"`
	FunctionIds      []string               `protobuf:"bytes,9,rep,name=function_ids,json=functionIds,proto3" json:"function_ids,omitempty"`
	Nonce            string                 `protobuf:"bytes,10,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContractExecutionRequest) Reset() {
	*x = ContractExecutionRequest{}
	mi := &file_scalar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractExecutionRequest) ProtoMessage() {}

func (x *ContractExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractExecutionRequest.ProtoReflect.Descriptor instead.
func (*ContractExecutionRequest) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{2}
}

func (x *ContractExecutionRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractExecutionRequest) GetContractArgument() string {
	if x != nil {
		return x.ContractArgument
	}
	return ""
}

func (x *ContractExecutionRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ContractExecutionRequest) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *ContractExecutionRequest) GetFunctionArgument() string {
	if x != nil {
		return x.FunctionArgument
	}
	return ""
}

func (x *ContractExecutionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ContractExecutionRequest) GetAuditorSignature() []byte {
	if x != nil {
		return x.AuditorSignature
	}
	return nil
}

func (x *ContractExecutionRequest) GetUseFunctionIds() bool {
	if x != nil {
		return x.UseFunctionIds
	}
	return false
}

func (x *ContractExecutionRequest) GetFunctionIds() []string {
	if x != nil {
		return x.FunctionIds
	}
	return nil
}

func (x *ContractExecutionRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type ContractExecutionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContractResult string                 `protobuf:"bytes,1,opt,name=contract_result,json=contractResult,proto3" json:"contract_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContractExecutionResponse) Reset() {
	*x = ContractExecutionResponse{}
	mi := &file_scalar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractExecutionResponse) ProtoMessage() {}

func (x *ContractExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractExecutionResponse.ProtoReflect.Descriptor instead.
func (*ContractExecutionResponse) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{3}
}

func (x *ContractExecutionResponse) GetContractResult() string {
	if x != nil {
		return x.ContractResult
	}
	return ""
}

var File_scalar_proto protoreflect.FileDescriptor

const file_scalar_proto_rawDesc = "" +
	"\n" +
	"\fscalar.proto\x12\x03rpc\x1a\x1bgoogle/protobuf/empty.proto\"y\n" +
	"\x1eCertificateRegistrationRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\vkey_version\x18\x02 \x01(\rR\n" +
	"keyVersion\x12\x19\n" +
	"\bcert_pem\x18\x03 \x01(\tR\acertPem\"x\n" +
	"\x19SecretRegistrationRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\vkey_version\x18\x02 \x01(\rR\n" +
	"keyVersion\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\"\x81\x03\n" +
	"\x18ContractExecutionRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12+\n" +
	"\x11contract_argument\x18\x02 \x01(\tR\x10contractArgument\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1f\n" +
	"\vkey_version\x18\x04 \x01(\rR\n" +
	"keyVersion\x12+\n" +
	"\x11function_argument\x18\x05 \x01(\tR\x10functionArgument\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12+\n" +
	"\x11auditor_signature\x18\a \x01(\fR\x10auditorSignature\x12(\n" +
	"\x10use_function_ids\x18\b \x01(\bR\x0euseFunctionIds\x12!\n" +
	"\ffunction_ids\x18\t \x03(\tR\vfunctionIds\x12\x14\n" +
	"\x05nonce\x18\n" +
	" \x01(\tR\x05nonce\"D\n" +
	"\x19ContractExecutionResponse\x12'\n" +
	"\x0fcontract_result\x18\x01 \x01(\tR\x0econtractResult2Z\n" +
	"\x06Ledger\x12P\n" +
	"\x0fExecuteContract\x12\x1d.rpc.ContractExecutionRequest\x1a\x1e.rpc.ContractExecutionResponse2\xa9\x01\n" +
	"\x10LedgerPrivileged\x12K\n" +
	"\fRegisterCert\x12#.rpc.CertificateRegistrationRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0eRegisterSecret\x12\x1e.rpc.SecretRegistrationRequest\x1a\x16.google.protobuf.EmptyB0Z.github.com/josh-wong/tegata/internal/audit/rpcb\x06proto3"

var (
	file_scalar_proto_rawDescOnce sync.Once
	file_scalar_proto_rawDescData []byte
)

func file_scalar_proto_rawDescGZIP() []byte {
	file_scalar_proto_rawDescOnce.Do(func() {
		file_scalar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalar_proto_rawDesc), len(file_scalar_proto_rawDesc)))
	})
	return file_scalar_proto_rawDescData
}

var file_scalar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scalar_proto_goTypes = []any{
	(*CertificateRegistrationRequest)(nil), // 0: rpc.CertificateRegistrationRequest
	(*SecretRegistrationRequest)(nil),      // 1: rpc.SecretRegistrationRequest
	(*ContractExecutionRequest)(nil),       // 2: rpc.ContractExecutionRequest
	(*ContractExecutionResponse)(nil),      // 3: rpc.ContractExecutionResponse
	(*emptypb.Empty)(nil),                  // 4: google.protobuf.Empty
}
var file_scalar_proto_depIdxs = []int32{
	2, // 0: rpc.Ledger.ExecuteContract:input_type -> rpc.ContractExecutionRequest
	0, // 1: rpc.LedgerPrivileged.RegisterCert:input_type -> rpc.CertificateRegistrationRequest
	1, // 2: rpc.LedgerPrivileged.RegisterSecret:input_type -> rpc.SecretRegistrationRequest
	3, // 3: rpc.Ledger.ExecuteContract:output_type -> rpc.ContractExecutionResponse
	4, // 4: rpc.LedgerPrivileged.RegisterCert:output_type -> google.protobuf.Empty
	4, // 5: rpc.LedgerPrivileged.RegisterSecret:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scalar_proto_init() }
func file_scalar_proto_init() {
	if File_scalar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalar_proto_rawDesc), len(file_scalar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_scalar_proto_goTypes,
		DependencyIndexes: file_scalar_proto_depIdxs,
		MessageInfos:      file_scalar_proto_msgTypes,
	}.Build()
	File_scalar_proto = out.File
	file_scalar_proto_goTypes = nil
	file_scalar_proto_depIdxs = nil
}
