// Subset of the ScalarDL 3.12 proto definitions used by the Tegata audit layer.
// Source: https://github.com/scalar-labs/scalardl/blob/v3.12.0/rpc/src/main/proto/scalar.proto
// Only the message types and RPCs required by Tegata are included.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: scalar.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ledger_ExecuteContract_FullMethodName = "/rpc.Ledger/ExecuteContract"
)

// LedgerClient is the client API for Ledger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerClient interface {
	ExecuteContract(ctx context.Context, in *ContractExecutionRequest, opts ...grpc.CallOption) (*ContractExecutionResponse, error)
}

type ledgerClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerClient(cc grpc.ClientConnInterface) LedgerClient {
	return &ledgerClient{cc}
}

func (c *ledgerClient) ExecuteContract(ctx context.Context, in *ContractExecutionRequest, opts ...grpc.CallOption) (*ContractExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractExecutionResponse)
	err := c.cc.Invoke(ctx, Ledger_ExecuteContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServer is the server API for Ledger service.
// All implementations must embed UnimplementedLedgerServer
// for forward compatibility.
type LedgerServer interface {
	ExecuteContract(context.Context, *ContractExecutionRequest) (*ContractExecutionResponse, error)
	mustEmbedUnimplementedLedgerServer()
}

// UnimplementedLedgerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServer struct{}

func (UnimplementedLedgerServer) ExecuteContract(context.Context, *ContractExecutionRequest) (*ContractExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteContract not implemented")
}
func (UnimplementedLedgerServer) mustEmbedUnimplementedLedgerServer() {}
func (UnimplementedLedgerServer) testEmbeddedByValue()                {}

// UnsafeLedgerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServer will
// result in compilation errors.
type UnsafeLedgerServer interface {
	mustEmbedUnimplementedLedgerServer()
}

func RegisterLedgerServer(s grpc.ServiceRegistrar, srv LedgerServer) {
	// If the following call panics, it indicates UnimplementedLedgerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ledger_ServiceDesc, srv)
}

func _Ledger_ExecuteContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).ExecuteContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ledger_ExecuteContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).ExecuteContract(ctx, req.(*ContractExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ledger_ServiceDesc is the grpc.ServiceDesc for Ledger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ledger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Ledger",
	HandlerType: (*LedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteContract",
			Handler:    _Ledger_ExecuteContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scalar.proto",
}

const (
	LedgerPrivileged_RegisterCert_FullMethodName   = "/rpc.LedgerPrivileged/RegisterCert"
	LedgerPrivileged_RegisterSecret_FullMethodName = "/rpc.LedgerPrivileged/RegisterSecret"
)

// LedgerPrivilegedClient is the client API for LedgerPrivileged service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerPrivilegedClient interface {
	RegisterCert(ctx context.Context, in *CertificateRegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterSecret(ctx context.Context, in *SecretRegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type ledgerPrivilegedClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerPrivilegedClient(cc grpc.ClientConnInterface) LedgerPrivilegedClient {
	return &ledgerPrivilegedClient{cc}
}

func (c *ledgerPrivilegedClient) RegisterCert(ctx context.Context, in *CertificateRegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LedgerPrivileged_RegisterCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerPrivilegedClient) RegisterSecret(ctx context.Context, in *SecretRegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LedgerPrivileged_RegisterSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerPrivilegedServer is the server API for LedgerPrivileged service.
// All implementations must embed UnimplementedLedgerPrivilegedServer
// for forward compatibility.
type LedgerPrivilegedServer interface {
	RegisterCert(context.Context, *CertificateRegistrationRequest) (*emptypb.Empty, error)
	RegisterSecret(context.Context, *SecretRegistrationRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedLedgerPrivilegedServer()
}

// UnimplementedLedgerPrivilegedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerPrivilegedServer struct{}

func (UnimplementedLedgerPrivilegedServer) RegisterCert(context.Context, *CertificateRegistrationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCert not implemented")
}
func (UnimplementedLedgerPrivilegedServer) RegisterSecret(context.Context, *SecretRegistrationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSecret not implemented")
}
func (UnimplementedLedgerPrivilegedServer) mustEmbedUnimplementedLedgerPrivilegedServer() {}
func (UnimplementedLedgerPrivilegedServer) testEmbeddedByValue()                          {}

// UnsafeLedgerPrivilegedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerPrivilegedServer will
// result in compilation errors.
type UnsafeLedgerPrivilegedServer interface {
	mustEmbedUnimplementedLedgerPrivilegedServer()
}

func RegisterLedgerPrivilegedServer(s grpc.ServiceRegistrar, srv LedgerPrivilegedServer) {
	// If the following call panics, it indicates UnimplementedLedgerPrivilegedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerPrivileged_ServiceDesc, srv)
}

func _LedgerPrivileged_RegisterCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerPrivilegedServer).RegisterCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerPrivileged_RegisterCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerPrivilegedServer).RegisterCert(ctx, req.(*CertificateRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerPrivileged_RegisterSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerPrivilegedServer).RegisterSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerPrivileged_RegisterSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerPrivilegedServer).RegisterSecret(ctx, req.(*SecretRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerPrivileged_ServiceDesc is the grpc.ServiceDesc for LedgerPrivileged service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerPrivileged_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.LedgerPrivileged",
	HandlerType: (*LedgerPrivilegedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterCert",
			Handler:    _LedgerPrivileged_RegisterCert_Handler,
		},
		{
			MethodName: "RegisterSecret",
			Handler:    _LedgerPrivileged_RegisterSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scalar.proto",
}
